backend:
 name: github
 repo: rabbani-esmaeil/portfolio-
 branch: main
media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "music"
    label: "پورتفولیو موسیقی"
    folder: "content/music"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "عنوان قطعه", name: "title", widget: "string"}
      - {label: "توضیحات", name: "description", widget: "text"}
      - {label: "فایل صوتی", name: "audio_file", widget: "file"}

  - name: "resume"
    label: "سوابق حرفه‌ای و اجرایی"
    folder: "content/resume"
    create: true
    slug: "item-{{year}}{{month}}{{day}}-{{minute}}"
    fields:
      - {label: "عنوان سمت / شغل", name: "title", widget: "string"}
      - {label: "نام سازمان یا شرکت", name: "company", widget: "string"}
      - {label: "بازه زمانی", name: "date_range", widget: "string"}
      - {label: "توضیحات", name: "body", widget: "markdown"}
