backend:
  name: github
  repo: rabbani-esmaeil/portfolio-
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "music"
    label: "پورتفولیو موسیقی"
    folder: "content/music"
    create: true
    fields:
      - {name: "title", label: "نام قطعه", widget: "string"}
      - {name: "description", label: "توضیحات", widget: "text"}
      - {name: "audio_file", label: "فایل صوتی (MP3)", widget: "file"}
